#! /bin/bash

rm -rf base_code main dev1 dev2
git init --bare base_code
git branch -m main

git clone base_code main
cd main
cp -rf ../../code/src .
git add src
git commit -m 'ajout initial'
git tag 0.0.0
git push --set-upstream origin 0.0.0
git push

cd ..
git clone base_code dev1 
cd dev1
git checkout -b b1 0.0.0

sed -i -e '4s/{/{ return 1.2*d->x;/' src/f.c

git add src/f.c
git commit -m 'modif f'
git push --set-upstream origin b1
cd ..

git clone base_code dev2 
cd dev2
git checkout -b b2 0.0.0

sed -i -e '4s/{/{ return 0.5*d->y;/' src/g.c

git add src/g.c
git commit -m 'modif g'
git push --set-upstream origin b2


